### ISSUE TITLE
Plugin crashes with manually set inspection list

### ISSUE THREAD

**Issue by mglukhikh** [JetBrains/inspection-plugin#10]
Inspection list:

```
    error('org.jetbrains.kotlin.idea.inspections.GradleKotlinxCoroutinesDeprecation')    
    error('org.jetbrains.kotlin.idea.inspections.KotlinInternalInJava')    
    error('org.jetbrains.kotlin.idea.inspections.KotlinInvalidBundleOrProperty')    
    error('org.jetbrains.kotlin.idea.inspections.MavenCoroutinesDeprecation')    
    error('org.jetbrains.kotlin.idea.inspections.ObsoleteExperimentalCoroutines')    
    warning('org.jetbrains.kotlin.idea.inspections.CanBeParameter')
    warning('org.jetbrains.kotlin.idea.inspections.CanBePrimaryConstructorProperty')    
    warning('org.jetbrains.kotlin.idea.inspections.CanBeVal')
    warning('org.jetbrains.kotlin.idea.inspections.ConflictingExtensionProperty')    
    warning('org.jetbrains.kotlin.idea.inspections.ConvertSecondaryConstructorToPrimary')    
    warning('org.jetbrains.kotlin.idea.inspections.DataClassPrivateConstructor')    
    warning('org.jetbrains.kotlin.idea.inspections.DeferredResultUnused')    
    ...
```

**Comment by mglukhikh** [comment]
In this case you should add the suffix `Inspection` to all names. See README

**Comment by yole** [comment]
Can we recognize inspection IDs without the word "Inspection" too?

**Comment by ayedo** [comment]
Thanks! 

Would you be interested in the list? I could add it to the repo / documentation if you want.

**Comment by mglukhikh** [comment]
@yole @ayedo Yes we surely can, but not right now.

**Comment by mglukhikh** [comment]
@ayedo You could add the whole list into this issue description or comment. It could be useful.

**Comment by ayedo** [comment]
OK, here it is:

`  error('org.jetbrains.kotlin.idea.inspections.GradleKotlinxCoroutinesDeprecationInspection')
    error('org.jetbrains.kotlin.idea.inspections.KotlinInternalInJavaInspection')
    error('org.jetbrains.kotlin.idea.inspections.KotlinInvalidBundleOrPropertyInspection')
    error('org.jetbrains.kotlin.idea.inspections.MavenCoroutinesDeprecationInspection')
    error('org.jetbrains.kotlin.idea.inspections.ObsoleteExperimentalCoroutinesInspection')
    warning('org.jetbrains.kotlin.idea.inspections.CanBeParameterInspection')
    warning('org.jetbrains.kotlin.idea.inspections.CanBePrimaryConstructorPropertyInspection')
    warning('org.jetbrains.kotlin.idea.inspections.CanBeValInspection')
    warning('org.jetbrains.kotlin.idea.inspections.ConflictingExtensionPropertyInspection')
    warning('org.jetbrains.kotlin.idea.inspections.ConvertSecondaryConstructorToPrimaryInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DataClassPrivateConstructorInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DeferredResultUnusedInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DeprecatedGradleDependencyInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DeprecatedMavenDependencyInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DestructuringWrongNameInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DifferentKotlinGradleVersionInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DifferentKotlinMavenVersionInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DifferentMavenStdlibVersionInspection')
    warning('org.jetbrains.kotlin.idea.inspections.DifferentStdlibGradleVersionInspection')
    warning('org.jetbrains.kotlin.idea.inspections.EmptyRangeInspection')
    warning('org.jetbrains.kotlin.idea.inspections.EqualsOrHashCodeInspection')
    warning('org.jetbrains.kotlin.idea.inspections.ExplicitThisInspection')
    warning('org.jetbrains.kotlin.idea.inspections.FakeJvmFieldConstantInspection')
    warning('org.jetbrains.kotlin.idea.inspections.JavaCollectionsStaticMethodOnImmutableListInspection')
    warning('org.jetbrains.kotlin.idea.inspections.KDocUnresolvedReferenceInspection')
    warning('org.jetbrains.kotlin.idea.inspections.KotlinDeprecationInspection')
    warning('org.jetbrains.kotlin.idea.inspections.KotlinMavenPluginPhaseInspection')
    warning('org.jetbrains.kotlin.idea.inspections.KotlinTestJUnitInspection')
    warning('org.jetbrains.kotlin.idea.inspections.KotlinUnusedImportInspection')
    warning('org.jetbrains.kotlin.idea.inspections.LeakingThisInspection')
    warning('org.jetbrains.kotlin.idea.inspections.MainFunctionReturnUnitInspection')
    warning('org.jetbrains.kotlin.idea.inspections.MigrateDiagnosticSuppressionInspection')
    warning('org.jetbrains.kotlin.idea.inspections.NestedLambdaShadowedImplicitParameterInspection')
    warning('org.jetbrains.kotlin.idea.inspections.OverridingDeprecatedMemberInspection')
    warning('org.jetbrains.kotlin.idea.inspections.PackageDirectoryMismatchInspection')
    warning('org.jetbrains.kotlin.idea.inspections.PlatformExtensionReceiverOfInlineInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RecursiveEqualsCallInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RecursivePropertyAccessorInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantCompanionReferenceInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantExplicitTypeInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantModalityModifierInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantSamConstructorInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantSemicolonInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantSuspendModifierInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantUnitExpressionInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantUnitReturnTypeInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RedundantVisibilityModifierInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RemoveForLoopIndicesInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RemoveRedundantBackticksInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RemoveRedundantCallsOfConversionMethodsInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RemoveRedundantSpreadOperatorInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RemoveSetterParameterTypeInspection')
    warning('org.jetbrains.kotlin.idea.inspections.RemoveSingleExpressionStringTemplateInspection')
    warning('org.jetbrains.kotlin.idea.inspections.ReplaceArrayEqualityOpWithArraysEqualsInspection')
    warning('org.jetbrains.kotlin.idea.inspections.ReplaceSingleLineLetInspection')
    warning('org.jetbrains.kotlin.idea.inspections.SelfAssignmentInspection')
    warning('org.jetbrains.kotlin.idea.inspections.UnusedEqualsInspection')
    warning('org.jetbrains.kotlin.idea.inspections.UnusedLambdaExpressionBodyInspection')
    warning('org.jetbrains.kotlin.idea.inspections.UnusedReceiverParameterInspection')
    warning('org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection')
    warning('org.jetbrains.kotlin.idea.inspections.UselessCallOnCollectionInspection')
    warning('org.jetbrains.kotlin.idea.inspections.UselessCallOnNotNullInspection')`

**Comment by mglukhikh** [comment]
Many thanks. I will probably rework this part in next version a little bit and then include the list into README or other documentation part.
