### ISSUE TITLE
Problem with custom source dirs

### ISSUE THREAD

**Issue by tasomaniac** [JetBrains/inspection-plugin#13]
When I do the following to add additional dirs to source sets, plugin just skips the files in those source dirs. 

```
sourceSets {
    main {
        kotlin {
            srcDirs += '/Users/foo/some/additional/folder'
        }
    }
}
```

When I do this, I got a warning that says `File Foo.kt is not in sources`. Don't know why you have this check but it looks like it does not cover all conditions. I found the following related line for reference: 
https://github.com/JetBrains/inspection-plugin/blob/master/runner/src/main/kotlin/org/jetbrains/idea/inspections/FileInfoRunner.kt#L39

**Comment by mglukhikh** [comment]
Thank you, I will re-check this place.
