### ISSUE TITLE
Only ConstantConditions in CI

### ISSUE THREAD

**Issue by mladen1nf** [JetBrains/inspection-plugin#22]
How to have just one check in CI? When I implemented the recommended code from the readme file, it starts to download 480mb. How can we avoid this?

**Comment by yole** [comment]
IntelliJ IDEA inspections are not packaged as standalone libraries; all inspections are part of the same IntelliJ IDEA distribution, and the download size doesn't depend on the number of enabled checks. It's not really feasible to change this at this time.
