### ISSUE TITLE
Plugin fails on Gradle 6.2.2/JDK13

### ISSUE THREAD

**Issue by christianhujer** [JetBrains/inspection-plugin#28]
When running the plugin from the `sample/` directory with Gradle 6.2.2, it fails with an exception `NoSuchMethodError` on `org.gradle.api.reporting.internal.TaskReportContainer.<init>(java.lang.Class, org.gradle.api.Task)`.

I've attached the stdout of running gradle 6.2.2 with `--stacktrace`.

[stderr.txt](https://github.com/JetBrains/inspection-plugin/files/4365146/stderr.txt)

**Comment by MatanSabag** [comment]
Faced same issue with Gradle 6.2

**Comment by jhansche** [comment]
See also #20 where this was just a deprecation warning in Gradle < 6

**Comment by mglukhikh** [comment]
Fixed by https://github.com/JetBrains/inspection-plugin/pull/33.
