### ISSUE TITLE
Support Android projects

### ISSUE THREAD

**Issue by gildor** [JetBrains/inspection-plugin#4]
Currently, inspections plugin creates tasks only for Java projects.
If I applied the plugin to Android projects no tasks available.

**Comment by mglukhikh** [comment]
See https://github.com/mglukhikh/inspection-sample-android as example of application to Android projects (in short, inspection plugin is applied to such projects in the same way as pmd, findbugs and other code quality plugins).

**Comment by gildor** [comment]
@mglukhikh Yes, I see now, there is task `inspections`. I will try again to integrate with my existing plugin, thanks
